version: '3.6'
volumes:
  mysql:
services:
    php:
        image: richarvey/nginx-php-fpm:latest
        container_name: php
        volumes:
            - "./nginx-site.conf:/var/www/html/conf/nginx/nginx-site.conf"
            - "./wp-config.php:/var/www/html/wp-config.php"
            - "./wordpress:/var/www/html"
            - "./wp-content:/var/www/html/wp-content"
            - ${THEME_DIR}:/var/www/html/wp-content/themes/${THEME_NAME}
            - ${PLUGIN_DIR}:/var/www/html/wp-content/plugins/${PLUGIN_NAME}
        ports:
            - 8080:80
            - 443:443
            - 9000:9000
        env_file: "./.env"
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wp_db
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 5001:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql
